### ISSUE TITLE
Add function to validate email address

### ISSUE THREAD

**Issue by cybergu0ck** [cybergu0ck/s2n2s2#8]
## Spec

- Add a function in `libs.utilitylib.utils` module to validate email address.
- The function signature must be `is_valid_email(address)`.
- The return value must be `True` if the email is valid and `False` is the email is invalid.
- Integreate it in main code.

**Comment by akshathprasad71012** [comment]
@cybergu0ck I would like to work on this. Can you assign it to me.

Thanks

**Comment by cybergu0ck** [comment]
@akshathprasad71012 You can create a branch off of `revamp` and create a PR after writing the function. At this point you cannot run the code but this task can be worked in isolation without the knowledge of this codebase. Let me know if you need any information.

**Comment by AndreVale69** [comment]
@cybergu0ck Hi, I would like to work on this issue, can you assign it to me? Since the low effort to bring this feature, I already do (and test) it. You can see the PR #9.

**Comment by cybergu0ck** [comment]
Thanks @AndreVale69
